config/routes.rb
Rails.application.routes.draw do

  
  root to: 'sessions#new'
  
  resources :users
  resources :admins
  
  
  get   'apikeys',      to: 'apikeys#show',     as: :apikey

  post  'login',        to: 'sessions#create',  as: :login
  get  'logout',     to: 'sessions#destroy', as: :logout
  
  get   'admin_login',   to: 'admins#new',       as: :admin_login
  post  'admin_login',   to: 'admins#create',    as: :admin_logged_in
  get   'admin_show',    to: 'admins#show',      as: :admin_show
  get 'admin_logout', to: 'admins#destroy',   as: :admin_logout
  
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :users_destroy
  
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base  
  
  validates :username, presence: true
  
  has_secure_password
end

app/models/api_key.rb
require 'securerandom'

class ApiKey < ActiveRecord::Base
  belongs_to :user
  before_create :generate_api_key
  
  validates :key, uniqueness: true
  
  #Source:
  #http://railscasts.com/episodes/352-securing-an-api?view=asciicast
  private
  
  def generate_api_key
    begin
      self.key = SecureRandom.hex
    end while self.class.exists?(key: key)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :api_key, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :email, presence: true, uniqueness: true, email_format: { message: "doesn't look like an email address" }
  
  has_secure_password
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :check_admin, only: [:show]


 
  def new
  end
  
  def create
    admin = Admin.find_by(username: params[:session][:username])
    
    if admin && admin.authenticate(params[:session][:password])
      admin_log_in admin
      redirect_to admin_show_path
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    admin_log_out
    flash[:info] = "Thanks for the visit, welcome back!"
    redirect_to admin_login_path
  end
  
  def show
    @users = User.all
  end
end

app/controllers/apikeys_controller.rb
class ApikeysController < ApplicationController
  before_action :check_user
  
  def show
    @key = @current_user.api_key
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  include AdminsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to apikey_path
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    log_out
    flash[:info] = "Thanks for the visit, welcome back!"
    redirect_to root_path
  end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, only: [:delete]
  before_action :check_admin, only: [:delete]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    user_apikey = ApiKey.new
    @user.api_key = user_apikey
    
    if @user.save
      log_in @user
      redirect_to apikey_path
    else
      render 'new'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    if is_admin_logged_in?
      flash[:success] = "Successfully deleted the user's account and API-key."
      redirect_to admin_login_path
    else
      flash[:warning] = "Your account and API-key has been deleted."
      redirect_to root_path
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
    
end

app/helpers/admins_helper.rb
module AdminsHelper
  
  def admin_log_in(admin)
    session[:admin_id] = admin.id
  end
  
  def admin_log_out
    session.delete(:admin_id)
    @current_admin = nil
  end
  
  def current_admin
    @current_admin ||= Admin.find_by(id: session[:admin_id])
  end
  
  def is_admin_logged_in?
    !current_admin.nil?
  end
  
  def check_admin
    unless is_admin_logged_in?
      log_out
      flash[:danger] = "Do log in!"
      redirect_to root_path
     end
  end
end

app/helpers/apikeys_helper.rb
module ApikeysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def is_logged_in?
    !current_user.nil?
  end
  
  def check_user
    unless is_logged_in?
      flash[:danger] = "Do log in!"
      redirect_to root_path
     end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/new.html.erb
<% content_for :title, "Welcome Admin - Sign in" %>

<div class="center jumbotron">
  <h1 class="text-center">Welcome Admin!</h1>
  <h3 class="text-center">Do sign in to view all user accounts</h3>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/flash_messages' %>
    <p><%= link_to "Register", new_user_path %> |
      <%= link_to "User Login", root_path %></p>
    <br />
    <br />
    <%= form_for(:session, url: admin_logged_in_path) do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>

      <%= f.label :password  %>
      <%= f.password_field :password, class: "form-control" %>

      <br />
      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/admins/show.html.erb
<% content_for :title, "Admin - Logged in" %>
<%= link_to "Logout", admin_logout_path%>
<br />

<div>
  <h2>User accounts and API-keys</h2>
  <table class="table table-hover">
      <th>
          <tr>
              <th>E-mail</th>
              <th>API-key</th>
              <th></th>
          </tr>
      </th>
          <% @users.each do |user| %>  
              <tr>
                <td><%= user.email %></td>
                <td><%= user.api_key.key %></td>
                <td><%= link_to "Delete", admin_destroy_user_path(user), method: :delete,  data: {confirm: 'User will be deleted, are you sure you want to proceed?'}, class: "btn btn-danger"%></td>
              </tr>
          <% end %>
    </table>
</div>

app/views/apikeys/show.html.erb
<% content_for :title, "Logged in" %>
<% content_for :screenname, @current_user.email %>
<%= link_to "Logout", logout_path%>
<br />

<h3>Din API-nyckel är:</h3>
<p><strong><%= @key.key %></strong></p>
<p><%= link_to "Delete", users_destroy_path(@current_user.id), method: :delete,  data: {confirm: 'Your API-key and account will be deleted, are you sure you want to proceed?'}, class: "btn btn-danger"%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if is_logged_in? %>
    <div class="alert alert-success" role="alert">Logged in as <%= yield(:screenname) %></div>
    <% end %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.full_messages.any? %>
<h3><strong>The register form has <%= pluralize(@user.errors.count, "error") %>:</strong></h3>
<% @user.errors.full_messages.each do |error_message| %>
    <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
       <%= error_message  %> <br />
    </div>
 <% end %>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">     
  <hr />
  <div class="container">
    <p class="text-center">App developed in <%= image_tag "rails.png", alt: "Rails logo" %> by Vivi Lam</p>
  </div>
</div>

app/views/shared/error_messages.html.erb
<% if @user.errors.any? %>
  <div>
    <h2>The register form has <%= pluralize(@user.errors.count, "error") %>:</h2>
    <ul>
      <%= @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% content_for :title, "Welcome - Register" %>

<div class="center jumbotron">
  <h1 class="text-center">Welcome!</h1>
  <h3 class="text-center">Do register to get your API-key</h3>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages' %>
    <div class="row">
      <p><%= link_to "User Login", root_path %> |
      <%= link_to "Admin Login", admin_login_path %></p>
    </div>
    <br />
    <%= form_for @user do |f| %>
      <div> 
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div> 
        <%= f.label :password %>
        <%= f.text_field :password, class: "form-control" %>
      </div>
       <div> 
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation, class: "form-control" %>
      </div>
      <br />
      <div> 
        <%= f.submit "Register", class: "btn btn-primary" %>
      </div>
    <% end %>
      
  </div>
</div>